name: smart_pet_care
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # تم تحديث إصدار الـ SDK ليتوافق مع أحدث المكتبات

dependencies:
  flutter:
    sdk: flutter

  # --- المكتبات التي أضفناها ---
  # Core & Backend
  http: ^1.2.1
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

  # UI & Widgets
  pinput: ^5.0.1
  fl_chart: ^1.0.0
  
  flutter_local_notifications: ^19.4.1
  supabase_flutter: ^2.5.8

  # Default Icon Pack
  cupertino_icons: ^1.0.8

dev_dependencies:
  names_launcher: ^0.0.1
  flutter_launcher_icons: "^0.11.0"

  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

names_launcher:
  name: "Pit Care"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
