# Project Base Gmail
name: Smart-Pet-Care-System
email : smartpetcaresystem@gmail.com
password : smart_care_pet_system_000

# HiveMQ
fname: Smart-Pet-
lname: Care-System
company: Smart-Pet-Care-System
email: smartpetcaresystem@gmail.com

# MQTT client
username: Smart-Pet-Care-System
password: Smart_care_pet_system_000

# GitHub
