# Project Base Gmail
name: Smart-Pet-Care-System
email : smartpetcaresystem@gmail.com
password : smart_care_pet_system_000

# HiveMQ
fname: Smart-Pet-
lname: Care-System
company: Smart-Pet-Care-System
email: smartpetcaresystem@gmail.com

# MQTT client
username: Smart-Pet-Care-System
password: Smart_care_pet_system_000

# MQTT broker
host: b8fde1f028ba4c73969c9d8905059c14.s1.eu.hivemq.cloud
port: 8883
websocket: 8884
client_id: ESP32_PetFeeder_01

